M48
; DRILL file KiCad 10.0.1 date 2026-05-11T01:31:18
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-11T01:31:18-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.000
%
G90
G05
T1
X146.243Y-67.156
T2
X166.242Y-67.156
T3
X169.15Y-77.15
X169.15Y-81.85
X169.255Y-95.85
X169.255Y-100.55
M30
